name: Primary checks

permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    timeout-minutes: 20
    strategy:
      max-parallel: 5
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        configs: [
          { os: ubuntu-24.04, cibw: true, cibw_archs: "x86_64,aarch64,i686" },
          { os: ubuntu-22.04, cibw: false, cibw_archs: "" },
          { os: macos-latest, cibw: true, cibw_archs: "arm64,x86_64" }
        ]

    runs-on: ${{ matrix.configs.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python_version }} and env
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies

      - name: Create virtual env
        run: |
          python -m venv .venv

      - name: Install package with dependencies
        run: |
          source .venv/bin/activate
          pip install -e '.[dev]'
          mkdir -p junit

      - name: Mypy
        run: |
          source .venv/bin/activate
          mypy --strict gpuq tests --junit-xml=junit/mypy-results.xml

      - name: Tests
        run: |
          source .venv/bin/activate
          pytest tests/ --junitxml=junit/test-results.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit/*.xml'

      - name: Install cibuildwheel
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.configs.cibw && matrix.python_version == '3.13' }}
        run: |
          source .venv/bin/activate
          pip install cibuildwheel

      - name: Build wheels
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.configs.cibw && matrix.python_version == '3.13' }}
        run: |
          source .venv/bin/activate
          python -m cibuildwheel --output-dir wheelhouse --archs "${{ matrix.configs.cibw_archs }}"

      - name: Upload wheels
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.configs.cibw && matrix.python_version == '3.13' }}
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.configs.os }}-python-${{ matrix.python_version }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
